<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonSchedulesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('lesson_schedules')->insert([
            [
                'lesson_master_id' => 1,
                'year_month' => '202503',
                'weekday' => 'MON',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'court_num' => 1,
                'staff_id' => 1,
                'sub_staff_id' => 2,
                'max_participants' => 8,
                'current_participants' => 5,
                'status' => 'OPEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 2,
                'year_month' => '202503',
                'weekday' => 'TUE',
                'start_time' => '10:00:00',
                'end_time' => '11:30:00',
                'court_num' => 2,
                'staff_id' => 2,
                'sub_staff_id' => 3,
                'max_participants' => 10,
                'current_participants' => 7,
                'status' => 'OPEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 3,
                'year_month' => '202503',
                'weekday' => 'WED',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'court_num' => 3,
                'staff_id' => 3,
                'sub_staff_id' => 4,
                'max_participants' => 6,
                'current_participants' => 6,
                'status' => 'CLOSED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 4,
                'year_month' => '202503',
                'weekday' => 'THU',
                'start_time' => '12:00:00',
                'end_time' => '13:30:00',
                'court_num' => 4,
                'staff_id' => 4,
                'sub_staff_id' => 1,
                'max_participants' => 12,
                'current_participants' => 8,
                'status' => 'OPEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 1,
                'year_month' => '202503',
                'weekday' => 'FRI',
                'start_time' => '13:00:00',
                'end_time' => '14:30:00',
                'court_num' => 1,
                'staff_id' => 1,
                'sub_staff_id' => 2,
                'max_participants' => 8,
                'current_participants' => 4,
                'status' => 'OPEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 2,
                'year_month' => '202503',
                'weekday' => 'SAT',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'court_num' => 2,
                'staff_id' => 2,
                'sub_staff_id' => 3,
                'max_participants' => 10,
                'current_participants' => 9,
                'status' => 'OPEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 3,
                'year_month' => '202503',
                'weekday' => 'SUN',
                'start_time' => '15:00:00',
                'end_time' => '16:30:00',
                'court_num' => 3,
                'staff_id' => 3,
                'sub_staff_id' => 4,
                'max_participants' => 6,
                'current_participants' => 6,
                'status' => 'CLOSED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 4,
                'year_month' => '202503',
                'weekday' => 'MON',
                'start_time' => '16:00:00',
                'end_time' => '17:30:00',
                'court_num' => 4,
                'staff_id' => 4,
                'sub_staff_id' => 1,
                'max_participants' => 12,
                'current_participants' => 10,
                'status' => 'OPEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 1,
                'year_month' => '202503',
                'weekday' => 'TUE',
                'start_time' => '17:00:00',
                'end_time' => '18:30:00',
                'court_num' => 1,
                'staff_id' => 1,
                'sub_staff_id' => 2,
                'max_participants' => 8,
                'current_participants' => 5,
                'status' => 'OPEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lesson_master_id' => 2,
                'year_month' => '202503',
                'weekday' => 'WED',
                'start_time' => '18:00:00',
                'end_time' => '19:30:00',
                'court_num' => 2,
                'staff_id' => 2,
                'sub_staff_id' => 3,
                'max_participants' => 10,
                'current_participants' => 7,
                'status' => 'OPEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
